### ISSUE TITLE
Is this dependency really needed?

### ISSUE THREAD

**Issue by ghost** [radarsu/ts-import#12]
https://github.com/SkylixGH/Hyper/tree/main/packages
We made our own TSImport module, and its 10 times as fast and compiles nearly instanstly

Feel free to take the code if you like

**Comment by radarsu** [comment]
Thanks, I'll give it a look, especially I'm curoius about the esbuild. Will probably improve this package when I have a little bit more of spare time!

**Comment by ghost** [comment]
I'll gladly implement this package for u with esbuild in a pr if u like
