### ISSUE TITLE
can't find " enum " 

### ISSUE THREAD

**Issue by heavenlian** [radarsu/ts-import#15]
part code:

my code :
import {
  Tabs,
  ETabsPosition
} from '@lui/core'
 <Tabs
      tabPosition={ETabsPosition.left}
      defaultActiveKey={defaultActiveKey}
    >
      <Tabs.TabPane tab={'基础信息')} key="1"></Tabs.TabPane >
</Tabs>
after  build with ts-import, 
I run in test environment：
<img width="473" alt="image" src="https://user-images.githubusercontent.com/5344794/161004578-ebe29dcc-e5ee-42a7-97ef-a97b97995d74.png">

**Comment by heavenlian** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/5344794/161005792-bd0ab758-6732-4818-9c60-429a49f83bcd.png">

**Comment by Areskul** [comment]
Ah! It happened to me while processing typescript  -> javascript with rollup. I think It doesn't like enums!

**Comment by radarsu** [comment]
Hey, it looks like your application is front-end code, and this module is for Node.js.
