### ISSUE TITLE
Cache problems

### ISSUE THREAD

**Issue by TagoDR** [radarsu/ts-import#16]
HI, I'm experiencing some problems using ts-include, it fells like there is something broken with imports and the cache.

I'm running a script outside the src folder, making some header files, to later include in the bundled code. I need to load some data from a dynamically generated and exported JSON from a .ts file inside src folder.

The reason I suspect is something to do with the cache is because, if I stubbornly try it 2 to 4 times in a roll it suddenly works as it should, however later changes made to the code are not inherited. Furthermore, if I delete the cache folder, it gives the errors again.
If I remove the dynamic parts of the .ts, and all imports, it works fine from the start.

This problem happens with any setting in tsconfig.json, even an empty one, no changes
Package.json also tried with minimal dependencies(ts and ts-import only) and with a full project, no changes

```
node ./build.js
node:internal/errors:845
  const err = new Error(message);
              ^

Error: Command failed: npx -p typescript tsc --project "C:\[...]PathToProject[...]\node_modules\ts-import\cache\[...]PathToProject[...]\tsconfig-[...].tmp.json"

    at ChildProcess.exithandler (node:child_process:387:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: 'npx -p typescript tsc --project "C:\[...]PathToProject[...]\node_modules\ts-import\cache\[...]PathToProject[...]\tsconfig-[...].tmp.json"
}

Node.js v18.1.0

```
My test
```js
import { tsImport } from 'ts-import';

tsImport.compile('./src/header.ts').then((result) => console.log(result)); // result.default should be a JSON

```

**Comment by radarsu** [comment]
Hey, I have been trying to replicate on Windows with Node 18, but without success. It's best if you try to execute `npx -p ...` command on your own and check it's output. Also, if you can provide a repository with such test case I can inspect and fix that.

**Comment by TagoDR** [comment]
I have figured it out.

Ts-import is not aware of my project types definitions(d.ts), therefore it was **silently** trowing typescript compile errors.
To fix it, I had to add a reference in my target file like this:

``` /// <reference path="globals.d.ts" />```

My  improvement suggestions would be:
1- To change the order of the error checking to make compile errors available  when loggers are provided;
The stdout would show typescript compile errors, however it never executed because the err block was executing before it.

index.ts lines 182 to 200, changed:
```ts
            childProcess.exec(compileCommand, async (err, stdout, stderr) => {  
                if (stdout.trim()) {
                    logger?.debug?.(stdout); 
                }

                if (stderr.trim()) {
                    logger?.debug?.(stderr);
                }

               if (err) {
                    logger?.error?.(err);
                    await fs.promises.rm(tmpTsConfigPath);
                    reject(err);
                    return;
                }

                await fs.promises.rm(tmpTsConfigPath);
                resolve(stdout);
            });
```
2- make it simpler to observe the errors, for example
```ts
tsImport('path/to/file.ts', loggerLevel = 'verbose');
```

instead of:
```ts
import { Compiler } from 'ts-import';
const tsImport = new Compiler({
    logger: {
      verbose: console.log,
      debug: console.log,
      info: console.log,
      warn: console.log,
      error: console.log,
    },
  });
  const s = await tsImport.compile('path/to/file.ts');
```
3- Document is the readme.md if custom types, in my case "declare interface Window and JQuery" overrides, are need in the import tree they need to be manually referenced.

Cheers.
