### ISSUE TITLE
BUG: cached files is not invalidated if compile option is changed

### ISSUE THREAD

**Issue by ornoone** [radarsu/ts-import#17]
it seem that if we change the options passed to load or loadSync, the cached file is used even if we expect a new file.

step to reproduce: 

start with this file: 

```
import * as tsImport from 'ts-import';

const main = async () => {
    const filePath = `file.ts`;
    const asyncResult = await tsImport.load(filePath);
};

void main();
```

update it to add the options : 

```
import * as tsImport from 'ts-import';

const main = async () => {
    const filePath = `file.ts`;
    const asyncResult = await tsImport.load(filePath, {
        transpileOptions: {
            compilerOptions: {
                experimentalDecorators: true,
                emitDecoratorMetadata: true,
            }
        }
    });
};

void main();
```
the module still does not contains any decorator metadata, since the cached files was created by the first execution.

something like using a hash of the compilation options to build the cache key would fix the issue

**Comment by radarsu** [comment]
Great idea!

EDIT:
I've added an option to turn off cache (`useCache: false`), which might be enough for now. I might revisit this use case some day.
