### ISSUE TITLE
generated .js files errors

### ISSUE THREAD

**Issue by agnoam** [radarsu/ts-import#21]
Hi,
I have a problem. I'm using this package to compile on the fly.
The code compile successfully.
But it cannot run it, because the generated code changed all the default imports into 
`require('<module-x>').default.<imported-function>` - and `default` key is `undefined`.

When I try to compile it with regular `tsc` the code run without no problems.
It compile into `const moduleX = __importDefault(require('<module-x>))`

Any idea?

**Comment by radarsu** [comment]
How are you importing library in TypeScript? Is it:
```ts
import tsImport from 'ts-import';
```
Or
```ts
import * as tsImport from 'ts-import';
```
Could you provide sample TypeScript file with tsconfig.json or a sample repo?

**Comment by agnoam** [comment]
I have used: `import * as tsImport from 'ts-import';` 
And I have used it like this:
```
importedFile = await tsImport.load(`${filePath}`, {
    mode: 'compile',
    compilerOptions: {
        compilerOptions: { 
            esModuleInterop: true,
            moduleResolution: "node",
            sourceMap: true,
            resolveJsonModule: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true
        }
    }
});
```

Source `.ts` file:
```
import dotenv from 'dotenv';
dotenv.config();
```

and the file I have error at compiled like this:
```
const dotenv_1 = require("dotenv");
dotenv_1.default.config();
```

And `dotenv_1.default` is `undefined`

**Comment by radarsu** [comment]
It seems to be related to compilerOptions setup only and likely not related to library implementation itself - can you try importing dotenv like this: `import * as dotenv from 'dotenv';` and let me know if it fixes the issue. If it doesn't feel free to reopen the issue.
