### ISSUE TITLE
Clear cached files

### ISSUE THREAD

**Issue by carlos-henrique-dev** [radarsu/ts-import#22]
Hi
I'm using this library to read files in a vite plugin I wrote for a personal project.
And in this plugin I need to read some specifc files inside the project and generate a new file
It works great but due to the cached files the output file does not update unless I restart the project.

Is there a way to make the caching optional or trigger a cache reset function?

**Comment by radarsu** [comment]
In `4.0.0-beta.7` version I've added a `useCache` flag that defaults to true:
```ts
const loaded = await tsImport.load(`load-me-without-cache.ts`, {
    useCache: false,
});
```
This should prevent caching the file and instead always compile it.
