### ISSUE TITLE
Is `compilerOptions.paths` working?

### ISSUE THREAD

**Issue by sneko** [radarsu/ts-import#28]
Hi @radarsu ,

First thank you for this library, it helped me :)

I tried to use:
```
const { generateRewrites, localizedRoutes } = tsImport.loadSync(`./src/utils/routes/list.ts`, {
  mode: tsImport.LoadMode.Compile,
  compilerOptions: {
    paths: {
      '@mediature/main/*': ['../../apps/main/*'],
    },
  },
});
```

And my `list.ts` has:
```
import { Lang, defineLocalizedRoute } from '@mediature/main/src/utils/routes/common';
...
```

But I get as error:
```
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '@mediature/main/src/utils/routes/common'
```

I tried different settings like:
```
  compilerOptions: {
    paths: {
      '@mediature/main/src/utils/routes/common': ['./src/utils/routes/common/docs/*'],
    },
  }
```

But it does not work neither. Which makes me wonder if this feature works with `ts-import`?

Thank you,

**EDIT:** note that this file where I do the compilation is aside my `tsconfig.json` and that `paths` inside this `tsconfig.json` are the exact same and work natively with `.ts` file.

Aside my issue, wondering if you library should let the possibility to load settings directly from `tsconfig.json`? Or does it imply potentially too many things whereas `ts-import` is I guess used just as a workaround in tricky situations?

**EDIT2:** In my GitHub actions the initial `tsImport.loadSync(`./src/utils/routes/list.ts`, {` is failing with:
```
docs:build: ERR! Error: ENOENT: no such file or directory, stat '/home/runner/work/mediature/mediature/apps/docs/src/utils/routes/list.ts'
```
... a bit weird since the standard `require('./src/utils/app-version.js');` works. I will give a try adding `__dirname` stuff.

**EDIT3:** issue in **EDIT2** has been fixed by using the `__dirname` like `const { generateRewrites, localizedRoutes } = tsImport.loadSync(path.resolve(__dirname, `./src/utils/routes/list.ts`), {`, I have no idea why it's needed since my local and GitHub executer current work directory is supposed to be the same since working for JS `require()` but that's ok ^^

**Comment by radarsu** [comment]
The problem with that is that tsconfig paths resolving seems to be responsibility of runtimes. Files with paths that should be mapped are not converted during compile time by tools like `tsc`, meaning this TypeScript file:
```ts
import { loadSync } from '@test/package';
```
Compiles to this JavaScript:
```js
const package_1 = require("@test/package");
```
And than CLI's like `ts-node` or other framework-provided handle mapping part (it could look like `ts-node --transpileOnly -r tsconfig-paths/register src/index.ts` or `node -r ts-node/register/transpile-only -r tsconfig-paths/register dist/index.js`). Such commands probably could consume this kind of JavaScript.

Given that your runtime which drives parent application (not ts-imported one) has that paths mapped and is using them itself, they might work when js file is imported.

This package though (I think), is mainly used to consume scripts, configuration files written in TypeScript, maybe dynamic functions, migration scripts etc. and works in a way that compiles TypeScript files to JavaScript, so I don't think this problem could be solved by it in a decent way (unless I learn more about tsconfig paths and discover such possibility).
