### ISSUE TITLE
Remove project path from cache folder

### ISSUE THREAD

**Issue by rtritto** [radarsu/ts-import#30]
### Description
Cache folder, by default, should not include project path folders but directle the transpiled files.

### Info
OS: Windows

### Steps to reproduce
- `yarn init -y`
- `yarn set version canary`
- `yarn add ts-import typescript`
- Create `test.ts` file:
```ts
const a = 1
```
- Create `start.js` file:
```js
const { loadSync } = require('ts-import')
loadSync('./test.ts')
```
- `yarn node start.js`
- Check `.cache/ts-import` folder

### Actual
`.cache\ts-import\C\<PROJECT_PATH>\test.js`

### Expected
`.cache\ts-import\test.js`

**Comment by radarsu** [comment]
That approach is purposedly chosen to allow less error-prone cache-checking for specific TypeScript configurations.

Is this a concern for other reason than very long paths which may approach OS path length limit?

**Comment by rtritto** [comment]
> Is this a concern for other reason than very long paths which may approach OS path length limit?

Yes, the project path is also redundant (`C:\<PROJECT_PATH>\.cache\ts-import\C\<PROJECT_PATH>`).

**Comment by radarsu** [comment]
As I said, this approach allowed me simplifying code logic behind cache-checking and making it more resilient. 

Although it could be removed, I don't feel like this is enough of a problem to work on that. Feel free though to raise a PR if you'd like to.
