### ISSUE TITLE
The requested module 'ts-import' does not provide an export named 'tsImport'

### ISSUE THREAD

**Issue by ae-King** [radarsu/ts-import#33]
```js
import { tsImport } from 'ts-import';
         ^^^^^^^^
SyntaxError: The requested module 'ts-import' does not provide an export named 'tsImport'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
```

I am importing as `import { tsImport } from 'ts-import';`
I am using ESM and v5.0.0

EDIT: I am following the READMEv2.md

**Comment by radarsu** [comment]
Hey, in versions `>4` it's:
```ts
import * as tsImport from 'ts-import';
```

**Comment by ae-King** [comment]
I am a little confused by ReadmeV2 is all since it has that format.

**Comment by radarsu** [comment]
README.v2.md is left in repo for version 2 of ts-import (`>=2.0.0`, `<3.0.0`), so it is older than README.md, which most up-to-date.
